# config.yaml for Snakemake with SLURM

# SLURM settings
slurm:
  slurm:
    partition: 'queue-1'  # Adjust this to your SLURM partition name
    nodes: 1
    ntasks-per-node: 1
    cpus-per-task: 4
    mem: '4G'
    time: '01:00:00'
    
  cluster:
    command: 'sbatch'
    status: 'squeue -j {job_id}'
    cancel: 'scancel {job_id}'
    nodes: 'scontrol show hostname {job_id}'
    
  default:
    jobs: 100
    max_threads: 8

# Conda settings
env:
  conda_env: 'snakemake7'
  conda_executable: '/home/ubuntu/miniconda3/bin/conda'  # Replace with actual path from `which conda`
  conda_config_path: '/home/ubuntu/.condarc'  # Replace with actual path if needed

# Paths to important files
additional:
  snakefile: 'Snakefile'
